import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/block/Navbar";
import UserProvider from "./components/UserProvider/UserProvider";
import Footer from "./components/block/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <UserProvider>
        <body className="bg-base-100 text-black">
          <Navbar />
          {children}
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}
